#!/usr/bin/env node
// Vendors the fonts the fly designs with (all SIL OFL) from @fontsource into fonts/, so the app
// works offline and exported SVG/PNG files can embed exactly the glyphs they use.
//   node tools/fetch_fonts.mjs
import { execSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, copyFileSync, existsSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FONTS } from '../src/design/type.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'fonts');
const SUBSETS = {
  latin: 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
  cyrillic: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
};
const slug = (f) => f.toLowerCase().replace(/\s+/g, '-');
const tmp = mkdtempSync(join(tmpdir(), 'df-fonts-'));
const fams = Object.keys(FONTS);
execSync('npm init -y', { cwd: tmp, stdio: 'ignore' });
execSync('npm i --silent ' + fams.map((f) => '@fontsource/' + slug(f)).join(' '), { cwd: tmp, stdio: 'inherit' });
rmSync(out, { recursive: true, force: true }); mkdirSync(out);
const manifest = {}; let css = '/* generated by tools/fetch_fonts.mjs — fonts are SIL Open Font License, via @fontsource */\n';
for (const fam of fams) {
  const s = slug(fam), dir = join(tmp, 'node_modules/@fontsource', s, 'files');
  const weights = [...new Set([...FONTS[fam].weights, ...(fam === 'Space Grotesk' ? [500] : [])])];
  for (const w of weights) {
    for (const [sub, range] of Object.entries(SUBSETS)) {
      const fn = `${s}-${sub}-${w}-normal.woff2`;
      if (!existsSync(join(dir, fn))) { if (sub === 'latin') console.warn('missing', fn); continue; }
      copyFileSync(join(dir, fn), join(out, fn));
      ((manifest[fam] ||= {})[w] ||= {})[sub] = fn;
      css += `@font-face{font-family:'${fam}';font-style:normal;font-weight:${w};font-display:swap;src:url(${fn}) format('woff2');unicode-range:${range}}\n`;
    }
  }
}
writeFileSync(join(out, 'manifest.json'), JSON.stringify({ subsets: SUBSETS, fonts: manifest }));
writeFileSync(join(out, 'fonts.css'), css);
try { copyFileSync(join(tmp, 'node_modules/@fontsource/inter/LICENSE'), join(out, 'LICENSE-OFL.txt')); } catch {}
rmSync(tmp, { recursive: true, force: true });
console.log('fonts:', Object.keys(manifest).length, 'families');
